package dto;

import java.io.Serializable;

public enum Action implements Serializable {
    REGISTER_CLIENT,
    REGISTER_MECHANIC,
    LOGIN,
    LOGOUT,

    CLIENT_CREATE_APPOINTMENT,
    CLIENT_LIST_APPOINTMENTS,
    CLIENT_ADD_NOTES,
    CLIENT_GET_NOTIFICATIONS,
    CLIENT_SUBMIT_FEEDBACK,

    MECHANIC_LIST_ASSIGNED,
    MECHANIC_UPDATE_STATUS,
    MECHANIC_ADD_PARTS_AND_DURATION,
    MECHANIC_LIST_PARTS,

    MANAGER_LIST_PENDING,
    MANAGER_ASSIGN_TO_MECHANIC,
    MANAGER_LIST_MECHANICS,
    MANAGER_GET_STATS,
    MANAGER_SET_SERVICE_PRICE,
    MANAGER_LIST_PRICES,
    MANAGER_LIST_PARTS,
    MANAGER_UPSERT_PART,
    MANAGER_LIST_FEEDBACK,

    ADMIN_LIST_USERS,
    ADMIN_ADD_MECHANIC,
    ADMIN_EDIT_MECHANIC,
    ADMIN_REMOVE_MECHANIC,
    ADMIN_PROMOTE_CLIENT_TO_MECHANIC,
    ADMIN_PROMOTE_CLIENT_TO_MANAGER
}